config/routes.rb
NextSgad::Engine.routes.draw do
  resources :employee_goal_activities
  resources :goal_units
  resources :employee_messages
  resources :messages
  resources :activities
  resources :results
  resources :justifications
  resources :attendances
  resources :functions
  resources :employee_goals
  resources :goals
  resources :assessments
  resources :configurations
  resources :positions
  resources :employees
  resources :departments

  get 'positions/orgchart', 'positions#orgchart'
end

app/models/next_sgad/activity.rb
module NextSgad
  class Activity < NextSgad::ApplicationRecord
    # def self.notification_result_validate(current_user, result)
    #   NextSgad::Activity.create(created_by: "#{current_user.first_name} #{current_user.last_name}", description: "Validou resultado")
    # end

    # def self.notification_result_invalidate(current_user, result)
    #   NextSgad::Activity.create(created_by: "#{current_user.first_name} #{current_user.last_name}", description: "Invalidou resultado")
    # end

    # def self.notification_new_result(current_user, result)
    #   NextSgad::Activity.create(created_by: "#{current_user.first_name} #{current_user.last_name}", description: "Adicionou novo resultado")
    # end

    # def self.notification_destroy_result(current_user, result)
    #   NextSgad::Activity.create(created_by: "#{current_user.first_name} #{current_user.last_name}", description: "Removido resultado")
    # end
  end
end

app/models/next_sgad/application_record.rb
module NextSgad
  class ApplicationRecord < ::ApplicationRecord
    self.abstract_class = true
    # scope :filter, -> (column, data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(column => data)}

    # def create_number
    #   tipo = self.class.name
    #   return unless tipo.eql?(NextSgad::Position.name) || tipo.eql?(NextSgad::Employee.name) || tipo.eql?(NextSgad::Department.name) || tipo.eql?(NextSgad::Function.name)
    #   i = self.class.all.map{|i| i.number.to_s.gsub(/\D/, '').to_i}.compact.sort.last || 0
    #   i = i + 1
    #   return unless number.blank?
    #   self.number = "#{self.class::INITIAL_LETTER}#{i.to_s.rjust(8, '0')}"
    # end

    # def create_number!
    #   self.create_number
    #   self.save
    # end
  end
end

app/models/next_sgad/assessment.rb
module NextSgad
  class Assessment < NextSgad::ApplicationRecord
    # has_many :employee_goals, dependent: :destroy
    # has_many :goals, dependent: :destroy
    # has_many :attendances, dependent: :destroy
    # has_many :employees_assessments, dependent: :destroy
    # enum status: {draft: 0, active: 1, inactive: 2, closed: 3}

    # scope :year, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(year: data)}
    # scope :status, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(status: data)}

    # validates_uniqueness_of :year
    # validates_presence_of :status, :skills_percentage, :year
    # validates :skills_percentage, :objectives_percentage, :attendance_percentage, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 100}
    # validate :percentages_values
    # validates :number_of_four_hours_delay_to_absence, :number_of_three_hours_delay_to_absence, :number_of_two_hours_delay_to_absence,
    #           :number_of_one_hour_delay_to_absence, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 365}
    
    # after_create :create_employees_assessments
    # after_save :update_assessments

    # # get the assessment from the #{year} or the last active or from the last year
    # def self.get_assessment(year = nil)
    #   if year.present?
    #     where(year: year).last
    #   else
    #     active.last || where(year: Time.now.year).last
    #   end
    # end

    # # get the last years assessment
    # def get_last_assessment
    #   NextSgad::Assessment.find_by(year: year - 1)
    # end

    # # check if last year assessments can be copied
    # def can_copy_last_years_skills?
    #   last_years_skills = get_last_assessment
    #   return false if last_years_skills.nil?
    #   last_years_skills.goals.skill.where.not(name: goals.skill.map(&:name)).exists?
    # end

    # # get last years skills
    # def dup_last_year_skills
    #   last_years_skills = get_last_assessment
    #   return NextSgad::Goal.none if last_years_skills.nil?
    #   last_years_skills.goals.skill.where.not(name: goals.skill.map(&:name)).map {|g| d = g.dup; d.function_ids = g.function_ids; d}
    # end

    # def employee_assessment(employee)
    #   assessment_value = (skills_assessment(employee) + objectives_assessment(employee) + attendance_assessment(employee)).round(1)
    #   empl_assessment = employees_assessments.where(employee_id: employee.id).where(manual: false).last
    #   if empl_assessment.present?
    #     empl_assessment.update_columns(result: assessment_value)
    #   end
    #   assessment_value
    # end

    # def skills_assessment(employee)
    #   this_employee_goals = employee_goals.skill.where(employee_id: employee.id)
    #   return 0 if this_employee_goals.size <= 0
    #   (skills_percentage/100) * (this_employee_goals.sum(&:final_assessment)/this_employee_goals.size)
    # end

    # def objectives_assessment(employee)
    #   this_employee_goals = employee_goals.objective.where(employee_id: employee.id)
    #   return 0 if this_employee_goals.size <= 0
    #   (objectives_percentage/100) * (this_employee_goals.sum(&:final_assessment)/this_employee_goals.size)
    # end

    # def attendance_assessment(employee)
    #   assessments_values = []
    #   NextSgad::Attendance.where(employee_id: employee.id).where("extract(year from date) = ?", year).group_by {|a| a.date.month}.each do |month, attendances_array_by_month|
    #     absences_number = 0
    #     attendances_array_by_month.group_by(&:status).each do |status, attendances_array|

    #       divide_by = case status
    #                     when 'four_hours_late'
    #                       number_of_four_hours_delay_to_absence
    #                     when 'three_hours_late'
    #                       number_of_three_hours_delay_to_absence

    #                     when 'two_hours_late'
    #                       number_of_two_hours_delay_to_absence

    #                     when 'one_hour_late'
    #                       number_of_one_hour_delay_to_absence

    #                     when 'absence'
    #                       1
    #                     else
    #                       0
    #                   end
    #       if divide_by > 0
    #         absences_number = absences_number + (attendances_array.size/divide_by).floor
    #       end
    #     end
    #     attendance_assessment_value = 0

    #     [max_absences_for_five, max_absences_for_four, max_absences_for_three, max_absences_for_two, max_absences_for_one].each_with_index do |v, index|
    #       if absences_number <= v
    #         attendance_assessment_value = 5 - index
    #         break
    #       end
    #     end

    #     assessments_values << (attendance_percentage/100) * attendance_assessment_value
    #   end
    #   if assessments_values.present?
    #     assessments_values.sum {|e| e}/assessments_values.size
    #   else
    #     0
    #   end
    # end

    # def attendance_assessment_by_month(employee)
    #   data = {}
    #   NextSgad::Attendance.where(employee_id: employee.id).where("extract(year from date) = ?", year).group_by {|a| a.date.strftime('%B')}.each do |month, attendances_array_by_month|
    #     absences_number = 0
    #     attendances_array_by_month.group_by(&:status).each do |status, attendances_array|

    #       divide_by = case status
    #                     when 'four_hours_late'
    #                       number_of_four_hours_delay_to_absence
    #                     when 'three_hours_late'
    #                       number_of_three_hours_delay_to_absence

    #                     when 'two_hours_late'
    #                       number_of_two_hours_delay_to_absence

    #                     when 'one_hour_late'
    #                       number_of_one_hour_delay_to_absence

    #                     when 'absence'
    #                       1
    #                     else
    #                       0
    #                   end
    #       if divide_by > 0
    #         absences_number = absences_number + (attendances_array.size/divide_by).floor
    #       end
    #     end
    #     attendance_assessment_value = 0

    #     [max_absences_for_five, max_absences_for_four, max_absences_for_three, max_absences_for_two, max_absences_for_one].each_with_index do |v, index|
    #       if absences_number <= v
    #         attendance_assessment_value = 5 - index
    #         break
    #       end
    #     end

    #     data[month] = [attendances_array_by_month.size, attendances_array_by_month.select(&:has_justification?).size, (attendance_percentage/100) * attendance_assessment_value]
    #   end
    #   return data
    # end

    # def update_assessments
    #   NextSgad::Employee.all.each{|e| employee_assessment(e)}
    # end

    # # get the last years assessment
    # def get_last_assessment
    #   NextSgad::Assessment.find_by(year: year - 1)
    # end

    # # check if last year assessments can be copied
    # def can_copy_last_years_skills?
    #   last_years_skills= get_last_assessment
    #   return false if last_years_skills.nil?
    #   last_years_skills.goals.skill.where.not(name: goals.skill.map(&:name)).exists?
    # end

    # # get last years skills
    # def dup_last_year_skills
    #   last_years_skills= get_last_assessment
    #   return NextSgad::Goal.none if last_years_skills.nil?
    #   last_years_skills.goals.skill.where.not(name: goals.skill.map(&:name)).map {|g| d = g.dup; d.function_ids = g.function_ids; d}
    # end

    # private
    # # check if the sum of all percentages is equal to 100
    # def percentages_values
    #   return if skills_percentage.nil? || objectives_percentage.nil? || attendance_percentage.nil?
    #   if skills_percentage + objectives_percentage + attendance_percentage != 100
    #     errors.add(:skills_percentage, 'A soma dos Objectivos, Competências e Assiduidade deve ser 100%')
    #     errors.add(:objectives_percentage, 'A soma dos Objectivos, Competências e Assiduidade deve ser 100%')
    #     errors.add(:attendance_percentage, 'A soma dos Objectivos, Competências e Assiduidade deve ser 100%')
    #   end
    # end

    # # create employee assessments for all amployees tha can be assessed
    # def create_employees_assessments
    #   begin
    #     emplos = NextSgad::Employee.can_be_assessed.map{|e| {employee_id: e.id}}
    #     # Creates an array like [{employee_id: 1}, {employee_id: 3}]
    #     NextSgad::EmployeeAssessment.create(emplos) do |f|
    #       f.assessment_id = id
    #     end
    #   rescue
    #     p $!.bactrace
    #   end
    # end
  end
end

app/models/next_sgad/attendance.rb
module NextSgad
  class Attendance < NextSgad::ApplicationRecord
    # belongs_to :position, optional: true
    # belongs_to :assessment, optional: true
    # belongs_to :employee
    # belongs_to :department, optional: true
    # has_and_belongs_to_many :justifications, association_foreign_key: :next_sgad_justification_id, foreign_key: :next_sgad_attendance_id
    # enum status: {four_hours_late: -4, three_hours_late: -3, two_hours_late: -2, one_hour_late: -1,  presence: 0, absence: 1, vacation: 2, authorized_leave: 3}
    # enum justification_status: {unjustified: -1, pending: 0, approved: 1, disapproved: 2, in_progress: 3}

    # scope :department_id, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(department_id: data)}
    # scope :year, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where_date(:date, year: data)}
    # scope :from_date, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where("date >= ?", data)}
    # scope :to_date, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where("date <= ?", data)}
    # #scope :from_to_date,   -> (data){nil.present? ? where(date: [data].flatten.compact.uniq.map{|f| f.split(',,,')}.flatten.uniq.split(' - ')[0]..data.split(' - ')[1])}
    # scope :employee_id, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(employee_id: data)}
    # scope :position_id, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(position_id: data)}
    # scope :assessment_id, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(assessment_id: data)}
    # scope :justification_status, -> (data) {data = [data].flatten.compact.uniq; data.blank? || data.include?('all') ? all : where(justification_status: data)}
    
    # validates :status, :date ,:employee_id, presence: true
    # validate :assessment_date
    # before_create :check_employee_data

    # # get all attendances with state absence or late
    # def self.all_absence
    #   where(status: [-4,-3,-2,-1,1])
    # end

    # # get attendances with justification
    # def self.with_justification
    #   where(justification_status: [0,1,2])
    # end

    # def self.without_justification
    #   where(status: [-4,-3,-2,-1,1]).where(justification_status: -1)
    # end

    # # true if an attendace has justification
    # def has_justification?
    #   pending? || approved? || disapproved? || in_progress?
    # end

    # def justification
    #   justifications.last
    # end

    # private
    # def assessment_date
      
    #   if date.blank?
    #     errors.add(:date, 'Escolha uma data')
    #   end

    #   if status.blank?
    #     errors.add(:status, 'Escolha o estado da presença')
    #   end

    #   return unless date.present?
      
    #   if NextSgad::Attendance.where.not(id: self.id).where(employee_id: self.employee_id).where("extract(day from date) = '#{self.date.day}'").where("extract(month from date) = '#{self.date.month}'").where("extract(year from date) = '#{self.date.year}'").present?
    #     errors.add(:date, 'Já tem foi registado para este dia')
    #   end

    #   if NextSgad::Assessment.find_by(year: date.year).nil?
    #     errors.add(:date, "Não tem Avaliação para o ano de  #{self.date.year}")
    #   end

    #   if new_record? && date.to_date > DateTime.now.to_date
    #     errors.add(:date, "Não pode marcar preenças adiantadas")
    #   end
    #   # TODO See translation from plugins
    # end

    # def check_employee_data
    #   return unless employee_id.present?
    #   self.position_id = employee.efective_position&.id
    #   self.department_id = position&.department&.id
    # end
  end
end

app/models/next_sgad/configuration.rb
module NextSgad
  class Configuration < NextSgad::ApplicationRecord
  end
end

app/models/next_sgad/employee_goal_activity.rb
module NextSgad
  class EmployeeGoalActivity < NextSgad::ApplicationRecord
    # belongs_to :employee_goal
    # belongs_to :creator, polymorphic: true

    # validates_presence_of :employee_goal_id, :creator_id, :creator_type, :description
  end
end

app/models/next_sgad/employee_message.rb
module NextSgad
  class EmployeeMessage < NextSgad::ApplicationRecord
  #   belongs_to :message
  #   belongs_to :employee
  #   enum status: {unread: 0, read: 1, removed: 2, unread_and_retracted: 3, read_and_retracted: 4}
  #   # unread :not yet read by the employee
  #   # read :read by the employee
  #   # removed :read and removed by the employee
  #   # unread_and_retracted :message retracted before the employee could read  it
  #   # read_and_retracted :message retracted afterthe employee could read it

  #  # recall message read and unread
  #   validates_presence_of :employee_id, :message_id
  #   validates_uniqueness_of :employee_id, scope: [:message_id]

  #   # marks a message as read and saves the date the message was read
  #   def mark_as_read(curr_employee = nil)
  #     return false unless curr_employee.class.name.eql?(NextSgad::Employee.name)
  #     return false if read?
  #     self.update(status: :read, read_at: DateTime.now)
  #   end
  end
end

app/controllers/next_sgad/activities_controller.rb
require_dependency "next_sgad/application_controller"

module NextSgad
  class ActivitiesController < ::ApplicationController
    before_action :set_activity, only: [:show, :edit, :update, :destroy]

    # GET /activities
    def index
      @activities = Activity.all
    end

    # GET /activities/1
    def show
    end


    # GET /activities/new
    def new
      @activity = Activity.new
    end

    # GET /activities/1/edit
    def edit
    end

    # POST /activities
    def create
      @activity = Activity.new(activity_params)

      if @activity.save
        redirect_to @activity, notice: 'Activity was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /activities/1
    def update
      if @activity.update(activity_params)
        redirect_to @activity, notice: 'Activity was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /activities/1
    def destroy
      @activity.destroy
      redirect_to activities_url, notice: 'Activity was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_activity
        @activity = Activity.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def activity_params
        params.require(:activity).permit(:created_by, :description)
      end
  end
end

app/views/next_sgad/positions/_form.html.erb
<%= form_with(model: position, local: true) do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :position_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :position_description %>
  </div>

  <div class="field">
    <%= form.label :position_id %>
    <%= form.select :position_id, options_for_select(NextSgad::Position.all.map{|v| [v.name, v.id]}) %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.select :department_id, options_for_select(NextSgad::Department.all.map{|v| [v.name, v.id]}) %>
  </div>

  <div class="field">
    <%= form.label :employee_id %>
    <%= form.select :employee_id, options_for_select(NextSgad::Employee.all.map{|v| [v.name, v.id]}) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/next_sgad/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/next_sgad/positions/index.html.erb
<!-- <div id="orgchart" data-orgchart-type="1"></div>
<div id="edit-panel" class="">
  <span id="chart-state-panel" class="radio-panel">
    <input type="radio" name="chart-state" id="rd-view" value="view" checked="true"><label for="rd-view">View</label>
    <input type="radio" name="chart-state" id="rd-edit" value="edit"><label for="rd-edit">Edit</label>
  </span>
  <label class="selected-node-group">selected node:</label>
  <input type="text" id="selected-node" class="selected-node-group">
  <label>new node:</label>
  <ul id="new-nodelist">
    <li><input type="text" class="new-node"></li>
  </ul>
  <i class="fa fa-plus-circle btn-inputs" id="btn-add-input"></i>
  <i class="fa fa-minus-circle btn-inputs" id="btn-remove-input"></i>
  <span id="node-type-panel" class="radio-panel">
    <input type="radio" name="node-type" id="rd-parent" value="parent"><label for="rd-parent">Parent(root)</label>
    <input type="radio" name="node-type" id="rd-child" value="children"><label for="rd-child">Child</label>
    <input type="radio" name="node-type" id="rd-sibling" value="siblings"><label for="rd-sibling">Sibling</label>
  </span>
  <button type="button" id="btn-add-nodes">Add</button>
  <button type="button" id="btn-delete-nodes">Delete</button>
  <button type="button" id="btn-reset">Reset</button>
</div>

<p id="notice"><%= notice %></p> -->

<h1>Positions</h1>


<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
  <thead>
    <tr>
      <th class="mdl-data-table__cell--non-numeric">Posição</th>
      <th class="mdl-data-table__cell--non-numeric">Empregado</th>
      <th class="mdl-data-table__cell--non-numeric">Nível</th>
      <th class="mdl-data-table__cell--non-numeric">Escalão</th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.name %></td>
        <td><%= position.description %></td>
        <td><%= position.next_sgad_position&.name %></td>
        <td><%= position.department %></td>
        <td><%= position.employee %></td>
        <td><%= position.number %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td class="mdl-data-table__cell--non-numeric"></td>
      <td></td>
      <td></td>
    </tr>

  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Position</th>
      <th>Department</th>
      <th>Employee</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.name %></td>
        <td><%= position.description %></td>
        <td><%= position.next_sgad_position&.name %></td>
        <td><%= position.department %></td>
        <td><%= position.employee %></td>
        <td><%= position.number %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/next_sgad/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Back', positions_path %>

app/views/next_sgad/positions/organigram.html.erb
<div id="orgchart" data-orgchart-type="1"></div>

app/views/next_sgad/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @position.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @position.description %>
</p>

<p>
  <strong>Position:</strong>
  <%= @position.position_id %>
</p>

<p>
  <strong>Department:</strong>
  <%= @position.department %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @position.employee %>
</p>

<p>
  <strong>Number:</strong>
  <%= @position.number %>
</p>

<%= link_to 'Edit', edit_position_path(@position) %> |
<%= link_to 'Back', positions_path %>